"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Dipindah ke environment variable supaya tidak ada secret key yang
# ke-commit ke repo publik (project ini "open source"). Kalau env var
# SECRET_KEY tidak diset (misal dev lokal), fallback ke key dev biasa —
# tapi untuk hosting sungguhan, WAJIB set env var SECRET_KEY sendiri.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-mad7xe9)@cr0!#os+b#8q@3nrs=*c7#f6(e+nl-j(c8^d*x*hl'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default tetap True untuk kemudahan dev lokal, tapi di hosting production
# set env var DEBUG=False.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# ── EMAIL (untuk link verifikasi email & reset password) ─────────────
# Default ke "console backend" — email gak dikirim sungguhan, isinya
# cuma di-print ke console/log server (cukup buat development & testing,
# link verifikasi/reset bisa dicopy manual dari log Railway).
#
# Buat PRODUCTION SUNGGUHAN, isi env var di bawah ini (misal pakai Gmail
# App Password, atau SMTP provider lain seperti SendGrid/Mailtrap), nanti
# otomatis pindah pakai SMTP backend asli:
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=emailkamu@gmail.com
#   EMAIL_HOST_PASSWORD=<app password, BUKAN password biasa>
#   EMAIL_USE_TLS=True
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@lms-academy.local')

# Dipakai buat bangun link absolut di email (https://domain.com/verify-email/<token>/)
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:8000')

# CSRF_TRUSTED_ORIGINS — WAJIB diisi untuk hosting di belakang proxy HTTPS
# (Railway, Render, dll). Tanpa ini, semua form POST (login admin, form
# komentar, dst) akan ditolak 403 "CSRF verification failed" walau
# ALLOWED_HOSTS sudah benar — keduanya adalah pengecekan yang berbeda.
# Otomatis di-generate dari ALLOWED_HOSTS supaya tidak perlu isi dua kali,
# selama domainnya bukan '*' (wildcard tidak valid untuk CSRF_TRUSTED_ORIGINS).
CSRF_TRUSTED_ORIGINS = [
    f"https://{host.strip()}"
    for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip() and host.strip() != '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
    'silk',
    'import_export',
    'ninja',
    'ninja_simple_jwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tasks.context_processors.current_user',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Sebelumnya ENGINE selalu sqlite3 padahal docker-compose.yml sudah
# menyiapkan container PostgreSQL terpisah — jadi container Postgres-nya
# tidak pernah benar-benar dipakai. Sekarang dibuat dinamis:
# - Jalan manual (python manage.py runserver) tanpa env var apapun -> SQLite,
#   gampang untuk dev sehari-hari, tidak perlu nyalain Postgres.
# - Jalan via docker-compose (DB_ENGINE=postgres di environment) -> otomatis
#   pakai PostgreSQL sesuai service "db" di docker-compose.yml.
if os.environ.get('DB_ENGINE') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'lms_db'),
            'USER': os.environ.get('DB_USER', 'lms_user'),
            'PASSWORD': os.environ.get('DB_PASS', 'lms_password'),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA — dipakai untuk file yang di-upload USER (foto profil), beda
# dengan STATIC (file aset bawaan project seperti CSS/JS). Sebelumnya
# belum ada konfigurasi MEDIA sama sekali di project ini.
#
# CATATAN PRODUCTION: kalau hosting di platform dengan filesystem
# ephemeral (Railway tanpa persistent volume), file di MEDIA_ROOT akan
# HILANG setiap kali ada deploy baru — beda dengan database (Postgres)
# yang persisten. Untuk skala project ini hal itu cukup diterima
# (foto profil reset tiap deploy), tapi untuk produksi sungguhan
# sebaiknya pakai object storage (S3-compatible) atau attach volume
# persistent ke folder media/.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CACHES — dipakai untuk fitur throttling (rate-limit) di tasks/api.py.
# Default Django (LocMemCache) tersimpan di MEMORI PER-PROCESS — kalau
# Gunicorn jalan dengan lebih dari 1 worker (otomatis terjadi kalau
# platform hosting set env var WEB_CONCURRENCY > 1), setiap worker punya
# cache-nya sendiri-sendiri, jadi hitungan rate-limit kepecah dan TIDAK
# PERNAH benar-benar memblokir. DatabaseCache dipakai sebagai gantinya
# supaya counter rate-limit dibagi bersama oleh semua worker (dan tahan
# kalau container restart), tanpa perlu infrastruktur tambahan (Redis dkk).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache_table",
    }
}

# WhiteNoise — serve static file (termasuk admin-custom.css) langsung dari
# Django tanpa perlu web server terpisah seperti Nginx. Wajib jalankan
# `python manage.py collectstatic` sebelum deploy ke hosting.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SILK SECURITY — sebelumnya TIDAK ADA pembatasan akses sama sekali di
# /silk/, artinya siapapun (bahkan yang belum login) bisa lihat semua
# query SQL & detail request internal. Sekarang dibatasi cuma staff
# Django (akun yang juga bisa akses /admin/).
SILKY_AUTHENTICATION = True
SILKY_AUTHORISATION = True
SILKY_PERMISSIONS = lambda user: user.is_staff

# ─── JWT Config (django-ninja-simple-jwt) ───────────────────
# Project ini pakai model User kustom (tasks.models.User), bukan
# django.contrib.auth.User — jadi claim map disesuaikan ke field
# yang benar-benar ada di model kustom tersebut. USE_STATELESS_AUTH
# tetap True (default) supaya validasi token cukup lewat tanda
# tangan JWT saja, tanpa perlu query ulang ke tabel auth bawaan Django.
NINJA_SIMPLE_JWT = {
    "USE_STATELESS_AUTH": True,
    "TOKEN_CLAIM_USER_ATTRIBUTE_MAP": {
        "user_id": "id",
        "username": "username",
        "fullname": "fullname",
        "email": "email",
    },
}

