# Generated by Django 5.2.13 on 2026-04-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment_course_coursecontent_coursemember_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.coursecontent'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.coursecontent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.coursemember')),
            ],
        ),
    ]
