# Generated by Django 5.2.13 on 2026-04-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_coursecontent_parent_alter_coursecontent_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='member',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Completion',
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
        migrations.DeleteModel(
            name='CourseMember',
        ),
    ]
