# Generated by Django 5.2.13 on 2026-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_user_password_course_image_url_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password123', max_length=100),
            preserve_default=False,
        ),
    ]
