# Generated by Django 5.2.13 on 2026-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
