# Generated by Django 5.2.13 on 2026-04-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_coursecontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/600x400?text=No+Image'),
        ),
    ]
