# Generated by Django 6.0.3 on 2026-06-16 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('std', 'Student'), ('tch', 'Teacher')], default='std', max_length=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to='tasks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tasks.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tasks.user')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
