# Generated by Django 6.0.6 on 2026-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_user_token_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://placehold.co/600x400/0a0f2c/ffffff?text=LMS'),
        ),
    ]
