# Generated by Django 6.0.6 on 2026-06-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['id']},
        ),
    ]
