# Generated by Django 6.0.6 on 2026-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_coursecontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Opsional. Isi total durasi video dalam detik (misal video 5:25 = 325 detik). Kalau diisi, durasi preview gratis materi pertama dihitung OTOMATIS sebagai persentase dari angka ini (lihat PREVIEW_PERCENTAGE di views.py). Kalau dikosongkan, dipakai durasi preview default (PREVIEW_DEFAULT_SECONDS).', null=True, verbose_name='Durasi Video (detik)'),
        ),
    ]
