# Generated by Django 6.0.6 on 2026-06-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_coursecontent_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='User wajib klik link verifikasi yang dikirim ke email sebelum bisa login di web.', verbose_name='Email Terverifikasi'),
        ),
    ]
