# Generated by Django 6.0.6 on 2026-06-25 19:43
#
# PENTING — migration ini SENGAJA ditulis manual (bukan auto-generate):
# project ini SUDAH LIVE di production dengan user asli yang sudah
# terdaftar SEBELUM fitur verifikasi email ini ada. Kalau field
# `is_verified` cuma di-default `False` tanpa migration ini, SEMUA user
# yang sudah ada bakal mendadak terkunci tidak bisa login sama sekali
# begitu update ini di-deploy — padahal mereka jelas belum pernah diminta
# verifikasi apa-apa waktu daftar dulu.
#
# Migration ini jalan SEKALI pas di-deploy, nge-mark SEMUA user yang
# SUDAH ADA di tabel saat itu sebagai sudah terverifikasi ("grandfather
# clause"). User yang daftar SETELAH ini akan tetap default belum
# terverifikasi (diatur eksplisit di view register, bukan dari sini),
# jadi cuma user baru yang kena wajib klik link verifikasi.
from django.db import migrations


def grandfather_existing_users(apps, schema_editor):
    User = apps.get_model('tasks', 'User')
    User.objects.filter(is_verified=False).update(is_verified=True)


def reverse_noop(apps, schema_editor):
    # Sengaja tidak di-reverse (tidak ada cara aman buat tau siapa yang
    # "harusnya" balik jadi belum-verified kalau migration ini di-undo).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_add_account_token'),
    ]

    operations = [
        migrations.RunPython(grandfather_existing_users, reverse_noop),
    ]
