# Generated by Django 6.0.6 on 2026-06-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_grandfather_existing_users_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(db_index=True, default='Umum', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20),
        ),
    ]
