# Generated by Django 6.0.6 on 2026-06-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=100, help_text='Jumlah maksimum peserta. Isi 0 kalau mau menutup pendaftaran sementara.'),
        ),
    ]
