# Generated by Django 6.0.6 on 2026-06-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_max_students_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(help_text='Harga dalam Rupiah. Isi 0 untuk kursus gratis.'),
        ),
    ]
