# Generated by Django 6.0.6 on 2026-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_price_positive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu. Materi dengan urutan sama diurutkan berdasarkan kapan dibuat.', verbose_name='Urutan Tampil'),
        ),
    ]
